# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe40189fa7b5a08c5dd4fcced3cdcfd7dea4901653f94e2f855997d07f1e91e76222be1a0e714e751f7595c84b9f9c47829c17e939787efd39b9bab853caf518

test:
  secret_key_base: 25209d1478ad0bfef7b9a1f9d8d1df6c29591b17da96aff5159ed175826d6512c8ee492c655faea32d904821e5ef68db923ca56caba9b04e737eec62f6d2a225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
